Adicionando novo recurso de envio de foto
lead-ifal/pc2i-app pull request #26
Opened 2022-01-20 01:23 UTC by J3Mateus

função de importar imagens

2022-01-23 23:03 UTC, felipealencar requested changes

2022-01-23 23:03 UTC, felipealencar commented on lib/preview_page.dart
> +class Previewpage extends StatelessWidget {
Esse nome classe não está seguindo o padrão CamelCase.

2022-01-23 23:03 UTC, felipealencar commented on lib/screens/new_culture_screen.dart
> +/*
Remover esse comentário no commit.

2022-01-23 23:03 UTC, felipealencar commented on lib/screens/new_culture_screen.dart
> +                      //   ElevatedButton(
?

2022-02-03 00:45 UTC, dhianapereira commented
Em reunião eu, @J3Mateus e @filipealvess, decidimos fechar esse PR, pois não atende a funcionalidade definida nos novos parâmetros da aplicação.

2022-02-03 00:45 UTC, closed without merging