Implementação do cadastro com a api e inicio da tela de "esqueci a se…
lead-ifal/pc2i-app pull request #6
Opened 2021-08-30 23:01 UTC by J3Mateus

…nha"

2021-09-01 14:43 UTC, dhianaslv requested changes
Olá, @J3Mateus :)

Então, fiz alguns apontamentos no teu código, que eu acredito que melhorará bastante o que você está desenvolvendo.

Mas antes de você fazer essas correções é importante que você dê merge da branch lead-ifal:master na sua branch J3Mateus:master, para que seu código seja atualizado. Quando você mesclar as duas branches, muito provavelmente vai dar conflitos e a pasta "components" na tua branch permaneça na mescla, mesmo que na branch do LEAD a pastas components agora se chame "widgets". Até mesmo agora está dando conflito na tela de signup, mas é bem simples de resolver. Qualquer dúvida sobre isso e sobre as observações que apontei no teu código, é só sinalizar aqui ou você também pode entrar em contato comigo que a gente marca uma call. :)

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/Password.dart
> +class password extends StatelessWidget {
Todas as classes precisam seguir o padrão da primeira letra maiúscula. Se eu não me engano essa classe stateless está funcionando como uma página de "esqueci a senha", logo, o nome da classe deveria ser algo mais descritivo como "ForgotPasswordScreen". Isso serve também para o nome do arquivo, no dart, nomeamos os arquivos sempre com letras minusculas e separadas por underline.

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/signup.dart
> +class Produto {
Essa classe Produto precisa estar em arquivo separado, dentro de uma pasta `models` na pasta `core`. Outra coisa é que pelos atributos, acho que se trata de um usuário, se for isso mesmo, o nome deveria ser User e não Produto.

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/signup.dart
> +  final String nome;
Os atributos precisam ser privados para garantir a segurança. a private do dart é o underline no inicio da variável.
Exemplo: _email

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/signup.dart
> +  final String nome;
Para acessar os valores dos atributos privados no dart basta criar métodos get, da seguinte forma:
`String get email => _email;`

A String sendo o tipo do atributo, o primeiro email sendo um nome qualquer da variável a seta que é a mesma coisa de usar as chaves e o return, e por fim, a variável que você deseja recuperar o valor.

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/signup.dart
> +class Produto {
Além disso, é preciso criar alguns métodos nessa classe para facilitar o envio e recuperação de dados do backend. Como o toJson e o fromJson. 

Exemplo: 

```
User.fromJson(Map json) {
    _name = json['name'];
    _email = json['email'];
  }
```

  ```
Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name'] = _name;
    data['email'] = _email;
    return data;
  }
```

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/signup.dart
> +  final String nome;
Outro detalhe é que você está escrevendo o código em português, o ideal é que escreva em inglês.

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/signup.dart
> +  Future<String> cadastroAPI(String url, Map jsonMap) async {
Sobre esta implementação, ela não deveria estar na interface do usuário, é necessário que exista uma separação. Seguindo a seguinte linha de pensamento:

1. User Interface
2. State Management 
3. Services
3. Api class (classe que consome do backend)

obs.: Essa Api class não é apenas um arquivo, a quantidade vai depender da sua aplicação, mas por enquanto, percebo que por hora, as únicas funcionalidades são de usuário, então seria uma classe UserApi (user_api.dart)

2021-09-01 14:43 UTC, dhianaslv commented on lib/screens/signup.dart
> +  Future<String> cadastroAPI(String url, Map jsonMap) async {
Então, seguindo essa linha de pensamento, essa implementação do cadastro deveria estar na pasta `data/api`, e não na interface do usuário.

2021-09-03 21:44 UTC, felipealencar requested changes
Os comentários de Dhiana foram transformados em issues, e adicionei mais um item a ser modificado.

2021-09-03 21:44 UTC, felipealencar commented on lib/screens/signup.dart
> +                    var url = "http://127.0.0.1:5000/users/new";
Utilizar um .env para definir a rota de cadastro do usuário.

2021-09-14 12:31 UTC, closed without merging